language: node_js
node_js:
  - "10"
env:
  global:    
    # DANGER_GITHUB_API_TOKEN
install:
  - bundle install
cache:
  bundler: true
  
jobs:
  include:
    - stage: danger
      script: danger --fail-on-errors=true
    - stage: bots
      script: danger --fail-on-errors=true
    - stage: tests
      script: run-tests
    - stage: deploy
      script: run-deployment

stages:
  - name: danger
    if: type IN (pull_request)
  - name: tests 
    if: type IN (pull_request, push) AND tag IS blank
  - name: bots
    if: type IN (pull_request)
  - name: deploy
    if: tag IS present